### ISSUE TITLE
CtrlPlanningSE2_PRM.cpp について

### ISSUE THREAD

**Issue by RyodoTanaka** [Ry0/OMPL_Sample#1]
今気づいたけど、このプログラムって内容的には
`CtrlPlanningSE2_PRM/CtrlPlanningSE2_PRM.cpp`
じゃなくて
`CtrlPlanningSE2_RRT/CtrlPlanningSE2_RRT.cpp`
じゃない？
ちなみに、NAISTのも間違ってる
まぁどっちでも良いんだけど。。。

**Comment by Ry0** [comment]
よく気が付きましたね
一応変更しておきました 
6aa1fec
